version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - /data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: kawla
      MONGO_INITDB_ROOT_PASSWORD: kawla

  mongo-express:
    image: mongo-express:latest
    container_name: my_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kawla
      ME_CONFIG_MONGODB_ADMINPASSWORD: kawla
      ME_CONFIG_MONGODB_SERVER: mongodb
  


